all: exercicio3-escritor exercicio3-leitor exercicio3-pai

exercicio3-escritor: exercicio3-escritor.c exercicio1.h

exercicio3-leitor: exercicio3-leitor.c exercicio1.h

exercicio3-pai: exercicio3-pai.c exercicio1.h exercicio2.h

clean:
	rm exercicio3-escritor
	rm exercicio3-leitor
	rm exercicio3-pai
